### ISSUE TITLE
There’s an error with handy-scroll.es6.js when used in a browser

### ISSUE THREAD

**Issue by phoenixsnake** [Amphiluke/handy-scroll#18]
In the Chrome console, I see this error message
```
handy-scroll.es6.js:47 Uncaught TypeError: Cannot read properties of null (reading 'querySelectorAll')
    at Object.$$ (handy-scroll.es6.js:47:44)
    at Object.mount (handy-scroll.es6.js:211:17)
    at handy-scroll.es6.js:279:25
    at dom.doc.addEventListener.once (handy-scroll.es6.js:26:73)
$$ @ handy-scroll.es6.js:47
mount @ handy-scroll.es6.js:211
(anonymous) @ handy-scroll.es6.js:279
dom.doc.addEventListener.once @ handy-scroll.es6.js:26
```

I have also tested it in Firefox and it shows this error message in the Firefox console:
```
Uncaught TypeError: dom.body is null
```

I have also attached an example file.
[error-report-handy-scroll-es6.zip](https://github.com/Amphiluke/handy-scroll/files/11132912/error-report-handy-scroll-es6.zip)

**Comment by phoenixsnake** [comment]
Thank you for your assistance.
